### ISSUE TITLE
Mixed content error http vs https

### ISSUE THREAD

**Issue by joanbales** [rochacbruno/Flask-GoogleMaps#12]
Hi,

I have a problem when I load my site with https protocol, and the script (gmaps) loads over http.

The message is the following:
was loaded over HTTPS, but requested an insecure script 'http://maps.googleapis.com/maps/api/js?sensor=false'. This request has been blocked; the content must be served over HTTPS.

Thx,

**Comment by rochacbruno** [comment]
Fixed!

**Comment by joanbales** [comment]
Thanks!

**Comment by joanbales** [comment]
Please, when you can, change

DEFAULT_ICON = 'http://maps.google.com/mapfiles/ms/icons/red-dot.png'to
DEFAULT_ICON = '//maps.google.com/mapfiles/ms/icons/red-dot.png'
Thanks!

**Comment by rochacbruno** [comment]
@joanbales done!
