### ISSUE TITLE
Marker description

### ISSUE THREAD

**Issue by milrrenmattar** [rochacbruno/Flask-GoogleMaps#16]
Hi! It is possible to add some text description to each marker?

**Comment by jclark754** [comment]
Hi @milrrenmattar, take a look here ![alt text](https://cloud.githubusercontent.com/assets/8108300/8969636/01994d80-3602-11e5-80ba-e0aa707b63a3.png)

By passing in the `infobox` parameter, you should be able to add a text description (or image, or any html) to each marker.

**Comment by rochacbruno** [comment]
:+1:
