### ISSUE TITLE
windows?

### ISSUE THREAD

**Issue by matteomircoli** [rochacbruno/Flask-GoogleMaps#37]
Hi,

I try  to use the sample on Windows and it doesn't work

Only linux?

**Comment by rochacbruno** [comment]
HI, never tested on windows @matteomircoli can you please give feedback on what errors you found?

**Comment by matteomircoli** [comment]
I obtain a strange 404 ....

If I clone the repository in Ubuntu it works... but if I import the project in Windows it doesn't work

**Comment by matteomircoli** [comment]
I solve  the problem... can I post the solutin, when some users use visual studio?

**Comment by rochacbruno** [comment]
@matteomircoli sure! please post what did you find.

**Comment by matteomircoli** [comment]
@rochacbruno it's possible find here the project [https://drive.google.com/file/d/0B4x2y-DuGWL_ZUQ2Q09iVmJ2LTg/view?usp=sharing](url)
