### ISSUE TITLE
marker

### ISSUE THREAD

**Issue by matteomircoli** [rochacbruno/Flask-GoogleMaps#39]
Hi,

in fullmap I want pass a series of markers lat long extract from mydatabase, but I don't understand How can I pass the list of dict.

like for m in lista_co:
         appo=[
              { 
                 'icon': '//maps.google.com/mapfiles/ms/icons/green-dot.png',
                 'lat': m['lat'],
                 'lng': m['long'],
                 'infobox': "Questo e' un marker di prova"
              }]
         markers.append(appo)
I want pass markers to Map ()...

**Comment by rochacbruno** [comment]
Use a list-comprehension

```python

map = Map(
    ...
    markers=[
        {
            'icon': icons.dots.green, 
            'lat': item['lat'], 
            'lng': item['lng'], 
            'infobox': "This is the box for item %s" % item
        } for item in lista_co
    ]
    ...    
)
```

or

```python
map = Map(...)
map.build_markers(markers)
```

or

```python
map = Map(...)
for m in lista_co:
    map.add_marker(m['lat'], m['lng'])
```

**Comment by matteomircoli** [comment]
many thanks
